### ISSUE TITLE
Failed to set LPeg lexer

### ISSUE THREAD

**Issue by NaitorStudios** [michal-h21/LuaXML#7]
The file is there, tried copying and renaming (to remove _x64) and still get the error...
If you could please help me, user defined languages are pretty bad, was hoping to use this instead...

**Comment by michal-h21** [comment]
I need more info about your setup and what you are trying to achieve. Do you use LuaXML included in TeX Live or the development version? What error do you get? Can you make a small script that shows it?

**Comment by NaitorStudios** [comment]
Oh, sorry, I've commented on the wrong project, must have mixed up the tabs... This was about Notepad++ Scintillua++ plugin...
